version: "3"
services: 
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/src

  consumer:
    image: wordpress
    restart: always
    volumes:
      - ./src:/var/www/html/src
    command: php /var/www/html/src/public/consumer.php

  rabbit-management:
    image: "rabbitmq:3-management-alpine"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      # - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./data:/var/lib/rabbitmq"
